SELECT 
 CV.[IDClave_400]
,CV.[IDClave_MDM]
,CV.[Validacion_IDClave]
,CV.[Código de Estado Cliente Llave A_Code_400]
,CV.[Código de Estado Cliente Llave A_Code_MDM]
,CV.[Validacion_Código de Estado Cliente Llave A_Code]
,CV.[Código de Ciudad Llave A_Code_400]
,CV.[Código de Ciudad Llave A_Code_MDM]
,CV.[Validacion_Código de Ciudad Llave A_Code]
,CV.[Código de Cuenta Llave A_400]
,CV.[Código de Cuenta Llave A_MDM]
,CV.[Validacion_Código de Cuenta Llave A_MDM]
,CV.[Nombre_400]
,CV.[Nombre_MDM]
,CV.[Validacion_Nombre]
,CV.[Registro Federal de Contribuyentes_400]
,CV.[Registro Federal de Contribuyentes_MDM]
,CV.[Validacion_Registro Federal de Contribuyentes]
,CV.[Código de Cadena_Code_400_C10CAD]
,CV.[Código de Cadena_Code_400_VCAD25]
,CV.[Código de Cadena_Code_MDM]
,CV.[Validacion_Código de Cadena_Code]
,CV.[Código de Tipo de Negocio de Cliente_Code_400]
,CV.[Código de Tipo de Negocio de Cliente_Code_MDM]
,CV.[Validacion_[Código de Tipo de Negocio de Cliente_Code]
,CV.[Código de Territorio_Code_400]
,CV.[Código de Territorio_Code_MDM]
,CV.[Validacion_Código de Territorio_Code_MDM]
,CV.[Código de Bodega_Code_400]
,CV.[Código de Bodega_Code_MDM]
,CV.[Validacion_[Código de Bodega_Code]
,CV.[Código de Ruta_Code_400]
,CV.[Código de Ruta_Code_MDM]
,CV.[Validacion_Código de Ruta_Code]
,CV.[Límite de Crédito_400]
,CV.[Límite de Crédito_MDM]
,CV.[Validacion_Límite de Crédito]
,CV.[Código de Autorizador Límite de Crédito_Code_400]
,CV.[Código de Autorizador Límite de Crédito_Code_MDM]
,CV.[Validacion_Código de Autorizador Límite de Crédito_Code]
,CV.[Código de Tipo de Cliente_Code_400]
,CV.[Código de Tipo de Cliente_Code_MDM]
,CV.[Validacion_Código de Tipo de Cliente_Code]
,CV.[Grupo de Clientes_400]
,CV.[Grupo de Clientes_MDM]
,CV.[Validacion_Grupo de Clientes]
,CV.[Pase Directo Manual_400]
,CV.[Pase Directo Manual_MDM]
,CV.[Validacion_Pase Directo Manual]
,CV.[Código de Status_Code_400]
,CV.[Código de Status_Code_MDM]
,CV.[Validacion_Código de Status_Code]
,CV.[Sucursal_400]
,CV.[Sucursal_MDM]
,CV.[Validacion_Sucursal]
,CV.[Nombre_Sucursal_400]
,CV.[Nombre_Sucursal_MDM]
,CV.[Validacion_Nombre_Sucursal]
,CV.[Código de País_F_400_C10EXT]
,CV.[Código de País_F_400_PAISFACTURAR]
,CV.[Código de País_F_400_FLPAIF]
,CV.[Nombre de País_Code_F_MDM]
,CV.[Código de País_Code_F_MDM]
,CV.[Validacion_Código de País_F_Code]
,CV.[Calle_F_400_CALLEFACTURAR]
,CV.[Calle_F_400_FLCALF]
,CV.[Calle_F_MDM]
,CV.[Validacion_Calle_F]
,CV.[Numero Exterior_F_400_NUMEROEXTFACTURAR]
,CV.[Numero Exterior_F_400_FLNUEF]
,CV.[Numero Exterior_F_MDM]
,CV.[Validacion_Numero Exterior_F]
,CV.[Numero Interior_F_400_NUMEROINTFACTURAR]
,CV.[Numero Interior_F_400_FLNUIN]
,CV.[Numero Interior_F_MDM]
,CV.[Validacion_Numero Interior_F]
,CV.[Código de Código Postal_F_400_FLCOPF]
,CV.[Código de Código Postal_F_400_CODIGOPOSTALFACTURAR]
,CV.[Código de Código Postal_F_400_C10COD]
,CV.[Código de Código Postal_F_MDM]
,CV.[Validacion_Código de Código Postal_F]
,CV.[Código de Colonia_F_400_C10COL]
,CV.[Código de Colonia_F_400_COLNIAFACTURAR]
,CV.[Código de Colonia_F_400_FLCOLF]
,CV.[Código de Colonia_F_MDM]
,CV.[Validacion_Código de Colonia_F]
,CV.[Código de Municipio_F_400_C10POB]
,CV.[Código de Municipio_F_400_MUNICIPIOFACTURAR]
,CV.[Código de Municipio_F_400_FLMUNF]
,CV.[Código de Municipio_F_MDM]
,CV.[Validacion_Código de Municipio_F]
,CV.[Código de Estado CP_F_400_FLEDOF]
,CV.[Código de Estado CP_F_400_ESTADOFACTURAR]
,CV.[Código de Estado CP_F_MDM]
,CV.[Validacion_Código de Estado CP_F_400]
,CV.[Latitud_400]
,CV.[Latitud_MDM]
,CV.[Validacion_latitud]
,CV.[Longitud_400]
,CV.[Longitud_MDM]
,CV.[Validacion_Longitud]
,CV.[Nombre Comercial Cliente_400]
,CV.[Nombre Comercial Cliente_MDM]
,CV.[ValidacioN_Nombre Comercial Cliente]
,CV.[Compañía Comercializadora_400]
,CV.[Compañia Comercializadora_MDM]
,CV.[ValidacioN_Compañia Comercializadora]
,CV.[Código de Compañia Principal_Code_400]
,CV.[Código de Compañia Principal_Code_MDM]
,CV.[ValidacioN_Compañia principal]
,CV.[Pase Directo Automático_400]
,CV.[Pase Directo Automático_MDM]
,CV.[ValidacioN_Pase Directo Automatico]
,CV.[Analista_400]
,CV.[Analista_MDM]
,CV.[Validacion_Analista]
FROM   HSVDMDDB01.MDMHERDEZCI.DBO.VALIDACION_CLIENTES_CAMPOXCAMPO_V2  CV WITH(NOLOCK)
INNER JOIN       HSVDMDDBPPSQL.[MDMHERDEZ].[mdm].[vwMDM_ModeloCliente] C WITH(NOLOCK) ON C.[Código de Cliente] = CV.IDCLAVE_MDM
WHERE  C.[Código de Status_Code] = 17
