USE MDMHERDEZ


-- STORED PROCEDURE: Validacion_Clientes_V2
-- TOTAL 106412

SELECT  CV.* 
FROM   HSVDMDDB01.MDMHERDEZCI.DBO.VALIDACION_CLIENTES_CAMPOXCAMPO_V2  CV WITH(NOLOCK)
INNER JOIN       HSVDMDDBPPSQL.[MDMHERDEZ].[mdm].[vwMDM_ModeloCliente] C WITH(NOLOCK) ON C.[Código de Cliente] = CV.IDCLAVE_MDM
WHERE  C.[Código de Status_Code] = 17

