SELECT TABLE_SCHEMA,TABLE_NAME,COLUMN_NAME,COLUMN_TEXT,COLUMN_HEADING,* 
FROM OPENQUERY(HDZ54,'SELECT * FROM QSYS2.SYSCOLUMNS 
WHERE 1=1
/*
AND (TABLE_SCHEMA=''HDZFAC''  AND TABLE_NAME=''FAC790F'' AND COLUMN_NAME LIKE ''%FLNUIN%'' )
OR  (TABLE_SCHEMA=''HDZCXC''  AND TABLE_NAME=''CC0100F'' AND COLUMN_NAME LIKE ''%NUMEROINTFACTURAR%'')
*/
AND (COLUMN_NAME LIKE ''%FLCOLF%'' )
ORDER BY TABLE_NAME,COLUMN_NAME')


--HDZFAC	FT790R	FLCOLF

--C10COL
--COLONIAFACTURAR
--FLCOLF




SELECT * FROM OPENQUERY(DEV_aS400, 'SELECT DISTINCT TABLE_SCHEMA,TABLE_NAME, COLUMN_NAME,  DATA_TYPE,LENGTH, COLUMN_TEXT
FROM QSYS2.SYSCOLUMNS WHERE 1=1
AND COLUMN_NAME   IN (''C10COL'',''COLNIAFACTURAR'',''FLCOLF'')
AND TABLE_NAME IN (''CC010F'',''FAC790F'',''CC0100F'',''CC009f'',''VE125F'',''CC020F'')
AND TABLE_SCHEMA IN (''HDZCXC'',''HDZFAC'')')
order by COLUMN_NAME


HDZCXC.CC010F	> C10COL				CHAR(25)
HDZCXC.CC0100F	> COLNIAFACTURAR		CHAR(50)
HDZFAC.FAC790F	> FLCOLF				CHAR(30)