
SELECT [TABLE_SCHEMA]TABLE_NAME,COLUMN_NAME,DATA_TYPE,[LENGTH]
FROM OPENQUERY(HDZ54,'SELECT * FROM QSYS2.SYSCOLUMNS WHERE 1=1
AND (COLUMN_NAME LIKE ''%C10POB%'' and TABLE_SCHEMA=''HDZCXC'' AND TABLE_NAME=''CC010F'')
or (COLUMN_NAME LIKE ''%FLMUNF%'' and TABLE_SCHEMA=''HDZFAC'' AND TABLE_NAME=''FAC790F'')
or  (COLUMN_NAME LIKE ''%MUNICIPIOFACTURAR%'' and TABLE_SCHEMA=''HDZCXC'' AND TABLE_NAME=''CC0100F'')
ORDER BY TABLE_NAME,COLUMN_NAME')




Código de Municipio_F_MDM