TRUNCATE TABLE [MDMHERDEZCI].[dbo].BS_DIF_MDM_AS400_MVC

SELECT COLUMN_NAME,'INSERT INTO  [MDMHERDEZCI].[dbo].BS_DIF_MDM_AS400_MVC (IDProducto, ValorAS400, ValorMDM,ValorMVC,DxTipoIssue) SELECT A.IDProducto, A.['+COLUMN_NAME+'] AS AS400,M.['+COLUMN_NAME+'] AS MDM , MV.['+COLUMN_NAME+'] AS MVC, '''  +COLUMN_NAME +''' AS TipoIssue FROM [MDMHERDEZCI].[dbo].BS_AS400 A LEFT JOIN [MDMHERDEZCI].[dbo].BS_MDM M ON A.IDProducto=M.IDProducto LEFT JOIN [MDMHERDEZCI].[dbo].BS_MVC MV on A.IDProducto=MV.idproducto WHERE A.['+COLUMN_NAME+']<>M.['+COLUMN_NAME+'] '
+ CASE WHEN COLUMN_NAME ='Linea' then ' OR A.['+COLUMN_NAME+']<>  CAST (MV.['+COLUMN_NAME+'] AS INT) ' ELSE 'OR A.['+COLUMN_NAME+']<> MV.['+COLUMN_NAME +']  ' END
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME='BS_AS400'
AND (COLUMN_NAME NOT LIKE '%[_]A' AND COLUMN_NAME NOT LIKE '%[_]G' )
AND COLUMN_NAME NOT IN (
'CB DUN14',
'CB EAN13',
'CB DUN14T',
'EAN13',
'DUN14',
'DUN14T'
)
UNION ALL
-- PARA CODIGO DE BARRAS RELLENAR HASTA 15 POSICIONES LOS 3 CAMPOS Y ASI COMPARAR
SELECT COLUMN_NAME,'INSERT INTO  [MDMHERDEZCI].[dbo].BS_DIF_MDM_AS400_MVC (IDProducto, ValorAS400, ValorMDM,ValorMVC,DxTipoIssue) SELECT A.IDProducto, A.['+COLUMN_NAME+'] AS AS400,M.['+COLUMN_NAME+'] AS MDM, MV.['+COLUMN_NAME+'] AS MVC  ,'''+COLUMN_NAME +''' AS TipoIssue  FROM [MDMHERDEZCI].[dbo].BS_AS400 A LEFT JOIN [MDMHERDEZCI].[dbo].BS_MDM M ON A.IDProducto=M.IDProducto LEFT JOIN [MDMHERDEZCI].[dbo].BS_MVC MV ON A.IDProducto=MV.IDProducto WHERE RIGHT(''000000000000000''+ISNULL(A.['+COLUMN_NAME+'] ,''0''),15)<> RIGHT(''000000000000000''+ISNULL(M.['+COLUMN_NAME+'] ,''0''),15) OR   RIGHT(''000000000000000''+ISNULL(A.['+COLUMN_NAME+'] ,''0''),15)<> RIGHT(''000000000000000''+ISNULL(MV.['+COLUMN_NAME+'] ,''0''),15) '
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME='BS_AS400'
AND (COLUMN_NAME NOT LIKE '%[_]A' AND COLUMN_NAME NOT LIKE '%[_]G' )
AND COLUMN_NAME  IN (
'CB DUN14',
'CB EAN13',
'CB DUN14T',
'EAN13',
'DUN14',
'DUN14T'
)



SELECT DXTIPOISSUE,COUNT(1)
FROM [MDMHERDEZCI].[dbo].BS_DIF_MDM_AS400_MVC
GROUP BY DXTIPOISSUE
ORDER BY 2 DESC

/* PARTE 2 */

TRUNCATE TABLE [MDMHERDEZCI].[dbo].BS_DIF_MDM_AS400_MVC

SELECT COLUMN_NAME,'INSERT INTO  [MDMHERDEZCI].[dbo].BS_DIF_MDM_AS400_MVC (IDProducto, ValorAS400, ValorMDM,ValorMVC,DxTipoIssue, KbDiferencia) 
SELECT A.IDProducto, A.['+COLUMN_NAME+'] AS AS400,M.['+COLUMN_NAME+'] AS MDM , MV.['+COLUMN_NAME+'] AS MVC, '''  +COLUMN_NAME +''' AS TipoIssue 
,'+ CASE  WHEN COLUMN_NAME ='Linea' THEN  'CASE  WHEN A.['+COLUMN_NAME+']<>M.['+COLUMN_NAME+'] OR A.['+COLUMN_NAME+']<> CAST (MV.['+COLUMN_NAME+'] AS INT) THEN 1 ELSE 0 END' ELSE ' CASE  WHEN A.['+COLUMN_NAME+']<>M.['+COLUMN_NAME+'] OR A.['+COLUMN_NAME+']<> MV.['+COLUMN_NAME+']  THEN 1 ELSE 0 END'  END
+' FROM [MDMHERDEZCI].[dbo].BS_AS400 A LEFT JOIN [MDMHERDEZCI].[dbo].BS_MDM M ON A.IDProducto=M.IDProducto LEFT JOIN [MDMHERDEZCI].[dbo].BS_MVC MV on A.IDProducto=MV.idproducto '
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME='BS_AS400'
AND (COLUMN_NAME NOT LIKE '%[_]A' AND COLUMN_NAME NOT LIKE '%[_]G' )
AND COLUMN_NAME NOT IN ('CB DUN14','CB EAN13','CB DUN14T','EAN13','DUN14','DUN14T')
UNION ALL

SELECT COLUMN_NAME,'INSERT INTO  [MDMHERDEZCI].[dbo].BS_DIF_MDM_AS400_MVC (IDProducto, ValorAS400, ValorMDM,ValorMVC,DxTipoIssue, KbDiferencia) 
SELECT A.IDProducto, A.['+COLUMN_NAME+'] AS AS400,M.['+COLUMN_NAME+'] AS MDM , MV.['+COLUMN_NAME+'] AS MVC, '''  +COLUMN_NAME +''' AS TipoIssue 
,'+ 'CASE WHEN RIGHT(''000000000000000''+ISNULL(A.['+COLUMN_NAME+'] ,''0''),15)<> RIGHT(''000000000000000''+ISNULL(M.['+COLUMN_NAME+'] ,''0''),15) OR   RIGHT(''000000000000000''+ISNULL(A.['+COLUMN_NAME+'] ,''0''),15)<> RIGHT(''000000000000000''+ISNULL(MV.['+COLUMN_NAME+'] ,''0''),15) THEN 1 ELSE 0 END'
+' FROM [MDMHERDEZCI].[dbo].BS_AS400 A LEFT JOIN [MDMHERDEZCI].[dbo].BS_MDM M ON A.IDProducto=M.IDProducto LEFT JOIN [MDMHERDEZCI].[dbo].BS_MVC MV on A.IDProducto=MV.idproducto '
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME='BS_AS400'
AND (COLUMN_NAME NOT LIKE '%[_]A' AND COLUMN_NAME NOT LIKE '%[_]G' )
AND COLUMN_NAME  IN ('CB DUN14','CB EAN13','CB DUN14T','EAN13','DUN14','DUN14T')


select dxtipoissue,count(1) CuentaIssues
from [MDMHERDEZCI].[dbo].BS_DIF_MDM_AS400_MVC 
where  kbdiferencia=1
group by dxtipoissue
having count(1)>0 
order by 2 desc
