
SELECT    
  P.[Número de Recurso]
, P.[Descripción Hérdez]
, TDP.[Código de Tipo de Producto],  TDP.[Nombre de Tipo de Producto]
, O.[Código de Origen] 
, O.[Nombre de Origen]
, M.[Código de Marca Armado Clave ME], M.[Nombre de Marca Armado Clave ME]
, C.[Codigo de Clase],C.Descripción as 'Nombre de Clase'
, P.[Peso Bruto]  	
, TE.[Código de Tipo de Envase],TE.[Nombre de Tipo de Envase]
, SC.[Clave de Subclase],SC.[Descripción Subclase]
, P.[Peso Neto]
, UDM_P.[Código de Unidad de Medida] AS 'Codigo de Unidad de Medida Peso'    ,UDM_P.[Nombre de Unidad de Medida] AS 'Nombre de Unidad de Medida Peso'
, UDM_E.[Código de Unidad de Medida] AS 'Codigo de Unidad de Medida Estandar', UDM_E.[Nombre de Unidad de Medida] AS 'Nombre de Unidad de Medida Estandar'
, P.[Piezas P Unidad de Venta]
, UDM_M.[Código de Unidad de Medida], UDM_M.[Nombre de Unidad de Medida]
, C_ABC.[Código de ABC],C_ABC.[Nombre de ABC]
, P.[Empaque Contenido]
, P.[Control de Lote]
, MRCD.[Código de Mercado], MRCD.[Nombre de Mercado]   
, P.[Consumo en Lote]
, TPO.[Código de Tipo], TPO.[Nombre de Tipo]
, LN.[Clave de Línea],ln.[Descripción de la Línea]
, P.[Indicador insuficiencia]
, P.[Código Saldo Recurso]
, P.[Consumo Teórico]
, P.[Clase Producto Producción]  	
, P.[Recurso Potente]
, P.[Factor de Potencia]
, P.[Fecha Efectividad Inicial]
, P.[Fecha Efectividad Final]
, P.[Factor Merma]
, P.[Justo a Tiempo]
, P.[Peligro BOL]
, P.[Línea Prod Producción]
, I.[Codigo de Categoria Impuesto],I.[Descripcion del Impuesto]
, ST.[Código de Status],ST.[Nombre de Status]
, P.Consecutivo
, P.Descripción
, SHMT.[Código de Sabor], SHMT.[Nombre de Sabor]
, PA_CLV.[Código de Planta Armado Clave ME] AS 'Código de Planta Armado' , PA_CLV.[Nombre de Planta Armado Clave ME] AS 'Nombre de Planta Armado Clave'				
, P.[Descripción del Recurso]
, P.[Contenido Neto]
, PA.[Cantidad Estiba x Hilera]
, PA.[Cantidad Estiba x Unidad]
, PA.[Cantidad de Camas x Tarima]
, PA.[Altura de Estiba]
, PA.[Días Antigüedad 1]
, PA.[Caja Altura]  	
, PA.[Caja Ancho]
, PA.[Caja Profundidad]
, PA.[Tarima Altura]
, PA.[Tarima Ancho]
, PA.[Tarima Profundidad]
, PA.[Recurso en Planta]
, PA.[Rotación Inventario]
, PA.[Ventana de Envío Directo]
, PC.[Código Nivel Costeo Fijo]
, TACSTO.[Código de Tipo Acum Costo],TACSTO.[Nombre de Tipo Acum Costo]
, PC.[Costo Estándar]
, PC.[Fecha Última Acumulación]
, PC.[Código Nivel Costeo]
, CUS.[Código de Costo Unitario Seleccionado],CUS.[Nombre de Costo Unitario Seleccionado]
, PC.[Costo Última Acumulación]
, PC.[Uso Valor Neto Realiz]
, CNACSTO.[Código de Clase Nivel Acum Costo],CNACSTO.[Nombre de Clase Nivel Acum Costo]
, PC.[Nuevo Costeo]
, CACSTO.[Código de Método Costeo Acum Costo],CACSTO.[Nombre de Método Costeo Acum Costo]
, PC.Entidad
, PC.[Tipo MP Prim p Costo]  	
, PC.[Nmb MP Prim p Costo]
, PAC.[Vida Útil]
, PAC.[Vida Útil Días]
, PAC.[Recep Misc Cód Clasific Localiz Predet]
, PAC.[Recep Prod Cód Clasific Localiz Predet]
, PCA.[Tiempo de seguridad]
, PCA.[Clase de reporte]  
, PCA.[Cód de localiz docum]
, PCA.[Línea Prod Mercadeo]
, PCA.[Cls Recurso Mercadeo]
, PCA.[Cód clase inven est]
, PCA.[Cambio Sobre Costo]
, PCA.[Tasa GI Variable]
, PCA.[Byte GI Variable]
, PCA.[Tabla Tasa GI Varibl]
, PCA.[Tasa GI Fija]
, PCA.[Valor Tabla GI Fija]
, PCA.[Byte GI Fijo]
, PCA.[Tabla Tasa GI Fijo]
, PCA.[Valor Neto Reablizab]
, PCA.[Costo Fijo]
, PCA.[Ctro Trabajo X Omis]
, PCA.[Grupo Turno X Omisi]
, PCA.[N Veces Recurs Usado]
, PCA.[TE Acum MP Cst Prim]
, PCA.[TE Acum MP Cst Pr hr]
, PCA.[TE Acum MP Cst Pr mn]
, PCA.[Nmb Tarea Escand rl]
, PCA.[Nmb Tarea Escand Sim]
, PCA.[N Secuencia Planif]
, PCA.[Loc Omis p Consumo]
, PCA.[Alm Omis p Consumo]
, PCA.[Código de mercancía]
, PCA.[Nivel Revisión Actl]
, PCA.[Ultimo Nivel Aceptab]
, PCA.[Número de comprador]
, PCA.[Nivel Servicio A]
, PCA.[Multiplic Capacidad]
, PCA.[Rqd De Cd Clsif Lclz]
, PCA.[TE 1 de OC]
, PCA.[TE 1 OC hrs]
, PCA.[TE 1 OC mns]
, PCA.[TE 2 OC]
, PCA.[TE 2 OC hrs]
, PCA.[TE 2 OC mns]
, PCA.[TE OC p Nva Versión]
, PCA.[TE OC Nva Ver hrs]
, PCA.[TE 1 MO]
, PCA.[TE 1 MO hrs]
, PCA.[TE 1 MO mns]
, PCA.[TE 2 MO]
, PCA.[TE 2 MO hrs]
, PCA.[TE 2 MO mns]
, PCA.[Ajustar TE OC Day]
, PCA.[Ajustar TE OC hrs]
, PCA.[Ajustar TE OC mns]
, PCA.[Ajustar TE MO day]
, PCA.[Ajustar TE MO hrs]
, PCA.[Ajustar TE OM mns]
, PCA.[Cnt Máxima TE OC]
, PCA.[Cnt Máxima TE MO]
, PCA.[TE Ventas]
, PCA.[TE Ventas hrs]
, PCA.[TE Ventas mns]
, PCA.[Código de gráficos]
, PCA.[Loc Omis p Bolt Prd]
, PCA.[Alm Omis p Bolt Prd]
, PCA.[Código 1 Cmt Omis]
, PCA.[Código 2 Cmt Omis]
, PCA.[Código 3 Cmt Omis]
, PCA.[Acept Var Cnt Inv]
, PCA.[Var Cnt Inv Omis]
, PCA.[Var Cnt Bol Cmplt]
, PCA.[Var Dflt Cnt Bol Cmplt]
, PCA.[Acept Var Preci Inv]
, PCA.[Var Cnt Défic Oms]
, PCA.[Var Precio Inv Omi]
, PCA.[Var Cnt Défct Acep]
, PCA.[Var Cnt sbr recp]
, PCA.[Var Cnt SR Oms]
, PCA.[Días Zona Firme]
, PCA.[Precio Unit Omisión]
, PCA.[Tabla Fch Rotación]
, PCA.[Clasif de transp]
, PCA.[Reclasif Automática]
, PCA.[Loclzcn Planta]
, PCA.[Fórmula química]
, PCA.[Imprim C A]
, PCA.[Núm caja]
, PCA.[Categoría reglamet]
, PCA.[Trans DI Grp Substit]
, PCA.[Trans RC Grp Substit]
, PCA.[Recurso Universal]
, PCA.[N Días Adel Cons DAC]
, PCA.[Familia Programas]
, PCA.CODIGODEBARRAS3
, PCA.CODIGODEBARRAS4
, PCA.CODIGODEBARRAS5
, PCA.CODIGODEBARRAS6
, PCA.CODIGODEBARRAS7
, PCA.CODIGODEBARRAS9
, PCA.CODIGODEBARRAS10
, PCA.UNIDADMEDIDAUNIDADLOGISTICA03
, PCA.UNIDADMEDIDAUNIDADLOGISTICA04
, PCA.UNIDADMEDIDAUNIDADLOGISTICA05
, PCA.UNIDADMEDIDAUNIDADLOGISTICA06
, PCA.UNIDADMEDIDAUNIDADLOGISTICA07
, PCA.UNIDADMEDIDAUNIDADLOGISTICA09
, PCA.UNIDADMEDIDAUNIDADLOGISTICA10
, PCA.[NÚMERO DE PROVEEDOR]
, PCA.[CAM TEMP ZONA]
, PCA.[UM CNT ABAS CAJA REC]
, PCA.[PTO ABAST CAJA RECOL]
, PCA.[UM PTO ABAS CAJA REC]
, PCA.[INDI MÍNI WM]
, PCA.[CNT DEMAN MÍNI WM]
, PCA.[UM DEMAND MÍN WM]
, PCA.[Ingrese el Almacén]
, PCA.[Ingrese Localización]
, PCA.[Ingrese Proveedor]
, PCA.[Unidad Medida Origen]
, PCA.[Unidad Medida Dest]
, PCA.Almacén
, PCA.[Núm de localización]
, PCA.[Número Proveedor]
, PCA.[Cantidad Origen 1]
, PCA.[Cantidad Destino 1]
, PCA.[Cantidad Origen 2]
, PCA.[Cantidad Destino 2]
, PCA.[Cantidad Origen 3]
, PCA.[Cantidad Destino 3]
, PCA.[Cantidad Origen 4]
, PCA.[Cantidad Destino 4]
, PCA.[Cantidad Origen 5]
, PCA.[Cantidad Destino 5]
, PCA.[TE OC Nva Ver mns]
, PCA.[Valor Tabla GI Var]
, PCA.[Días Antigüedad 2]
, PCA.[Días Antigüedad 3]
, PCA.[Días Antigüedad 4]
, PCA.[Días Antigüedad 5]
, PCA.[RECUR RASTR UNID]
, UDM_CMPRS.[Código de Unidad de Medida],UDM_CMPRS.[Nombre de Unidad de Medida]
, PCOMPRAS.[Cód Aprob Proveedor Y N]
, PCOMPRAS.[Código Imponible]
, CAT_CMPRS.[Código de Categoría de Compras], CAT_CMPRS.[Nombre de Categoría de Compras]
, SUBCAT_CMPRS.[Código de Subcategoría de Compras],SUBCAT_CMPRS.[Nombre de Subcategoría de Compras]
, CAT_NEG.[Código de Categoría de Negociación],CAT_NEG.[Nombre de Categoría de Negociación]
, PEXT.[Descripción Larga del Producto]
, PEXT.[Número del Producto]
, PEXT.[Número Ficha Técnica]
, PEXT.[Unidad Empaque]
, T_ENV.[Código de Tipo de Envase],T_ENV.[Nombre de Tipo de Envase]
, CLV_MRCA.[Código de Clave de Marca],CLV_MRCA.[Nombre de Clave de Marca]
, CMPNIA_ALF.[Código de Compañia Alfabetica],CMPNIA_ALF.[Nombre de Compañia Alfabetica]
, CMPNIA_GS1.[Código de Compañia GS1],CMPNIA_GS1.[Nombre de Compañia GS1]
, PEXT.[Código de Barras GS1 8]
, PEXT.[Consecutivo EAN 13]
, PEXT.[Consecutivo DUN14]
, PEXT.[Consecutivo DUN14T]
, PEXT.[Cambio EAN 13]
, PEXT.[Cambio DUN14]
, PEXT.[Cambio DUN14T]
, CMPNIA_NUM.[Código de Compañia Numérica],CMPNIA_NUM.[Nombre de Compañia Numérica]
, PEXT.[Compañía AMECE]
, PEXT.[Precio de Venta]
, PEXT.[EAN 13]
, PEXT.DUN14
, PEXT.DUN14T
, PEXT.[ID de Origen]
, IMPSTS.[Codigo de Categoria Impuesto],IMPSTS.[Nombre de Impuestos]
, COMEN.[Código de Comentarios CB],COMEN.[Nombre de Comentarios CB]
, PEXT.[Componentes de la OF Pack]
, TDALMAC.[Código de Tipo de Almacenaje],TDALMAC.[Nombre de Tipo de Almacenaje]
, PDO.[Código de Politica de Orden],PDO.[Nombre de Politica de Orden]
, CDO.[Código de Origen],CDO.[Nombre de Origen]
, PPLAN.[Número de Planificador]
, PPLAN.[Cantidad Orden Prog Fijo]
, PPLAN.[Indicador Nueva Planif]
, PPLAN.[Ctn Orden Progr Min]
, PPLAN.[Inventario de Seguridad]
, COD_PMP.[Código de PMP],COD_PMP.[Nombre de PMP]
, PPLAN.[Ctn Orden Progr Máx]
, TMP_PLAN.[Código de Tipo MP Planificación],TMP_PLAN.[Nombre de Tipo MP Planificación]
, PPLAN.[Nombre MP Planif Prima]
, PPLAN.[Ctn Orden Progr Mul]
, PPLAN.[Cód Nivel Planif Fijo]
, PPLAN.[Cód Nivel Planificación]
, PPLAN.[Código Plazo Corto]
, PPLAN.[Código Plazo Largo]
, PPLAN.[Calc de Nvo Tiempo Espera]
, PPLAN.[Código Plazo Intermedio]
, PPLAN.[Código de Identificación]
, PPLAN.[Días de Abastecimiento]
, FH.[Código de Formato Helados],FH.[Nombre de Formato Helados]
, C_H.[Código de CAT Helados],C_H.[Nombre de CAT Helados]
, C_P_H.[Código de Presentación Helados],C_P_H.[Nombre de Presentación Helados]
, PH.DSD
, PCDB.[Peso Neto EAN 13]
, PCDB.[Peso Bruto EAN 13]
, UDM_EAN13_PESO.[Código de Unidad de Medida] AS 'Código de Unidad de Medida Peso EAN13',UDM_EAN13_PESO.[Nombre de Unidad de Medida] as 'Nombre de Unidad de Medida Peso EAN13'
, UDM_EAN13_STD.[Código de Unidad de Medida] 'Código de Unidad de Medida Estandar EAN13',UDM_EAN13_STD.[Nombre de Unidad de Medida]  as 'Nombre de Unidad de Medida Estandar EAN13'
, UDM_EAN13_DIM.[Código de Unidad de Medida] AS 'Código de Unidad de Medida Dimension EAN13', UDM_EAN13_DIM.[Nombre de Unidad de Medida] as 'Nombre de Unidad de Medida Dimension EAN13'
, PCDB.[Volúmen Exterior EAN 13]
, PCDB.[Dimensión Interior Alto EAN 13]
, PCDB.[Dimensión Ext Alto EAN 13]
, PCDB.[Dimensión Interior Ancho EAN 13]
, PCDB.[Dimensión Ext Ancho EAN 13]
, PCDB.[Dimensión Interior Profundo EAN 13]
, PCDB.[Dimensión Ext Profundo EAN 13]
, UDM_DUN14_PESO.[Código de Unidad de Medida] AS 'Código de Unidad de Medida Peso DUN14',UDM_DUN14_PESO.[Nombre de Unidad de Medida] as 'Nombre de Unidad de Medida Peso DUN14'
, UDM_DUN14_STD.[Código de Unidad de Medida] 'Código de Unidad de Medida Estandar DUN14',UDM_DUN14_STD.[Nombre de Unidad de Medida]  as 'Nombre de Unidad de Medida Estandar DUN14'
, UDM_DUN14_DIM.[Código de Unidad de Medida] AS 'Código de Unidad de Medida Dimension DUN14', UDM_DUN14_DIM.[Nombre de Unidad de Medida] as 'Nombre de Unidad de Medida Dimension DUN14'
, PCDB.[Peso Neto DUN14]
, PCDB.[Peso Bruto DUN14]
, PCDB.[Volúmen Exterior DUN14]
, PCDB.[Dimensión Interior Alto DUN14]
, PCDB.[Dimensión Ext Alto DUN14]
, PCDB.[Dimensión Interior Ancho DUN14]
, PCDB.[Dimensión Ext Ancho DUN14]
, PCDB.[Dimensión Interior Profundo DUN14]
, PCDB.[Dimensión Ext Profundo DUN14]
, UDM_DUN14T_PESO.[Código de Unidad de Medida] AS 'Código de Unidad de Medida Peso DUN14T',UDM_DUN14T_PESO.[Nombre de Unidad de Medida] as 'Nombre de Unidad de Medida Peso DUN14T'
, UDM_DUN14T_STD.[Código de Unidad de Medida] 'Código de Unidad de Medida Estandar DUN14T',UDM_DUN14T_STD.[Nombre de Unidad de Medida]  as 'Nombre de Unidad de Medida Estandar DUN14T'
, UDM_DUN14T_DIM.[Código de Unidad de Medida] AS 'Código de Unidad de Medida Dimension DUN14T', UDM_DUN14T_DIM.[Nombre de Unidad de Medida] as 'Nombre de Unidad de Medida Dimension DUN14T'
, PCDB.[Peso Neto DUN14T]						
, PCDB.[Peso Bruto DUN14T]
, PCDB.[Volúmen Exterior DUN14T]						
, PCDB.[Dimensión Interior Alto DUN14T]
, PCDB.[Dimensión Ext Alto DUN14T]
, PCDB.[Dimensión Interior Ancho DUN14T]
, PCDB.[Dimensión Ext Ancho DUN14T]
, PCDB.[Dimensión Interior Profundo DUN14T]						
, PCDB.[Dimensión Ext Profundo DUN14T]
, PDLD.[Tipo Producto Demantra]  
FROM  			    HSVDMDDBPPSQL.MDMHERDEZ.mdm.vwMDM_Productos AS P 
LEFT OUTER JOIN  	HSVDMDDBPPSQL.MDMHERDEZ.mdm.vwMDM_Productos_Almacenes AS PA ON PA.[Codigo de Producto_ID] = P.ID 
LEFT OUTER JOIN  	HSVDMDDBPPSQL.MDMHERDEZ.mdm.vWMDM_Productos_Costos AS PC ON PC.[Codigo de Producto_ID] = P.ID AND PC.Entidad = 'ALMACENES' 
LEFT OUTER JOIN  	HSVDMDDBPPSQL.MDMHERDEZ.mdm.vwMDM_ProductosAseguramientoCalidad AS PAC ON PAC.[Codigo de Producto_ID] = P.ID 
LEFT OUTER JOIN  	HSVDMDDBPPSQL.MDMHERDEZ.mdm.vwMDM_ProductosCampos_Adicionales AS PCA ON PCA.[Codigo de Producto_ID] = P.ID 
LEFT OUTER JOIN  	HSVDMDDBPPSQL.MDMHERDEZ.mdm.vwMDM_ProductosCompras AS PCOMPRAS ON PCOMPRAS.[Codigo de Producto_ID] = P.ID 
LEFT OUTER JOIN  	HSVDMDDBPPSQL.MDMHERDEZ.mdm.vwMDM_ProductosExtendido AS PEXT ON PEXT.[Codigo de Producto_ID] = P.ID 
LEFT OUTER JOIN  	HSVDMDDBPPSQL.MDMHERDEZ.mdm.vwMDM_ProductosPlaneacion AS PPLAN ON PPLAN.[Codigo de Producto_ID] = P.ID 
LEFT OUTER JOIN  	HSVDMDDBPPSQL.MDMHERDEZ.mdm.vwMDM_ModeloProductosHelados AS PH ON PH.[Codigo de Producto_ID] = P.ID 
LEFT OUTER JOIN  	HSVDMDDBPPSQL.MDMHERDEZ.mdm.vwMDM_Productos_Codigo_de_Barras AS PCDB ON PCDB.[Codigo de Producto_ID] = P.ID 
LEFT OUTER JOIN  	HSVDMDDBPPSQL.MDMHERDEZ.mdm.vwMDM_PlandeDemanda AS PDLD ON PDLD.[Codigo de Producto_ID] = P.ID 
LEFT OUTER JOIN  	HSVDMDDBPPSQL.MDMHERDEZ.mdm.vwMDM_Sabor_Helados AS SHMT ON PH.Sabor_ID = SHMT.ID 
LEFT OUTER JOIN  	HSVDMDDBPPSQL.MDMHERDEZ.mdm.vwMDM_Origen O on  O.ID=P.Origen_ID
LEFT OUTER JOIN  	HSVDMDDBPPSQL.MDMHERDEZ.mdm.vwMDM_TipoDeProducto  TDP ON TDP.ID=P.[Tipo de Producto_ID] 
LEFT OUTER JOIN  	HSVDMDDBPPSQL.MDMHERDEZ.mdm.vwMDM_MarcaPDescripción M on M.ID=P.[Marca P Descripción_ID]
LEFT OUTER JOIN  	HSVDMDDBPPSQL.MDMHERDEZ.mdm.vwMDM_Clase C on C.ID=P.Clase_ID
LEFT OUTER JOIN  	HSVDMDDBPPSQL.MDMHERDEZ.mdm.vmMDM_PD_Tipo_De_Envase TE ON TE.ID=P.[Tipo de Envase_ID]
LEFT OUTER JOIN  	HSVDMDDBPPSQL.MDMHERDEZ.mdm.vwMDM_SubClase SC ON SC.ID=P.[Sub Clase_ID]
LEFT OUTER JOIN  	HSVDMDDBPPSQL.MDMHERDEZ.mdm.vwMDM_UnidadesDeMedida UDM_P ON UDM_P.ID=P.[Unidad de Medida de Peso_ID]
LEFT OUTER JOIN  	HSVDMDDBPPSQL.MDMHERDEZ.mdm.vwMDM_UnidadesDeMedida UDM_E ON UDM_E.ID=P.[Unidad de Medida Estándar_ID]
LEFT OUTER JOIN  	HSVDMDDBPPSQL.MDMHERDEZ.mdm.vwMDM_UnidadesDeMedida UDM_M ON UDM_M.ID=P.[Unidad de Medida P Descripción_ID]
LEFT OUTER JOIN  	HSVDMDDBPPSQL.MDMHERDEZ.mdm.vwMDM_CódigoABC  AS C_ABC ON C_ABC.ID=P.[Código ABC_ID]
LEFT OUTER JOIN  	HSVDMDDBPPSQL.MDMHERDEZ.mdm.vwMDM_PD_Mercado AS MRCD ON MRCD.ID=P.Mercado_ID
LEFT OUTER JOIN  	HSVDMDDBPPSQL.MDMHERDEZ.mdm.vwMDM_Tipo AS TPO ON TPO.ID=P.Tipo_ID
LEFT OUTER JOIN  	HSVDMDDBPPSQL.MDMHERDEZ.mdm.vwMDM_Linea LN on LN.ID=p.Linea_ID
LEFT OUTER JOIN  	HSVDMDDBPPSQL.MDMHERDEZ.mdm.vwMDM_Impuestos  I on I.ID=P.[Catégoria de Impuesto_ID]
LEFT OUTER JOIN  	HSVDMDDBPPSQL.MDMHERDEZ.mdm.vwMDM_Miscelaneos1 ST  on ST.ID=P.Status_ID
LEFT OUTER JOIN  	HSVDMDDBPPSQL.MDMHERDEZ.mdm.vwMDM_PlantaArmadoClaveMe PA_CLV on PA_CLV.ID=P.[Planta Armado Clave_ID]
LEFT OUTER JOIN     HSVDMDDBPPSQL.MDMHERDEZ.mdm.vwMDM_Tipo_Acum_Costo TACSTO				   ON TACSTO.ID      = PC.[Código Tipo Acum Costo_ID] 
LEFT OUTER JOIN     HSVDMDDBPPSQL.MDMHERDEZ.mdm.vwMDM_Costo_Unitario_Seleccionado CUS ON CUS.ID=PC.[Costo Unitario Seleccionado_ID] AND PC.Entidad='ALMACENES'
LEFT OUTER JOIN     HSVDMDDBPPSQL.MDMHERDEZ.mdm.vwMDM_Clase_Nivel_Acum_Costo CNACSTO ON CNACSTO.ID=PC.[Cód Clase Nivel Acum Cost_ID] AND PC.Entidad='ALMACENES'
LEFT OUTER JOIN     HSVDMDDBPPSQL.MDMHERDEZ.mdm.vwMDM_Metodo_Costeo_Acum_Costo CACSTO ON CACSTO.ID=PC.[Mét Costeo Acum Costo_ID] AND PC.Entidad='ALMACENES'
LEFT OUTER JOIN     HSVDMDDBPPSQL.MDMHERDEZ.mdm.vwMDM_UnidadesDeMedida UDM_CMPRS ON UDM_CMPRS.ID = PCOMPRAS.[UM Compras_ID]
LEFT OUTER JOIN     HSVDMDDBPPSQL.MDMHERDEZ.mdm.viw_SYSTEM_21_1280_CHILDATTRIBUTES CAT_CMPRS on CAT_CMPRS.ID= PCOMPRAS.[Categoría de Compras_ID]
LEFT OUTER JOIN     HSVDMDDBPPSQL.MDMHERDEZ.mdm.viw_SYSTEM_21_1338_CHILDATTRIBUTES SUBCAT_CMPRS ON SUBCAT_CMPRS.ID=PCOMPRAS.[Subcategoría de Compras_ID]
LEFT OUTER JOIN     HSVDMDDBPPSQL.MDMHERDEZ.mdm.vwMDM_CategoriaDeNegociacion CAT_NEG  on CAT_NEG.ID=PCOMPRAS.[Categoría de Negociación_ID]
LEFT OUTER JOIN     HSVDMDDBPPSQL.MDMHERDEZ.mdm.vwMDM_TipoDeEnvase T_ENV ON T_ENV.ID=PEXT.[Tipo Empaque Primario_ID]
LEFT OUTER JOIN     HSVDMDDBPPSQL.MDMHERDEZ.mdm.vwMDM_ClaveDeMarca CLV_MRCA ON CLV_MRCA.ID = PEXT.[Clave de Marca_ID]
LEFT OUTER JOIN     HSVDMDDBPPSQL.MDMHERDEZ.mdm.vwMDM_CompaniaAlfabetica CMPNIA_ALF ON CMPNIA_ALF.ID=PEXT.[Clave Compañía Alfanum_ID]
LEFT OUTER JOIN     HSVDMDDBPPSQL.MDMHERDEZ.mdm.vwMDM_PD_CompaniasGS1 CMPNIA_GS1 on CMPNIA_GS1.ID = PEXT.[Compañía GS1_ID]
LEFT OUTER JOIN     HSVDMDDBPPSQL.MDMHERDEZ.mdm.vwMDM_PD_CompaniasNumerica CMPNIA_NUM ON CMPNIA_NUM.ID= PEXT.[Número de Compañía_ID]
LEFT OUTER JOIN     HSVDMDDBPPSQL.MDMHERDEZ.mdm.vwMDM_Impuestos IMPSTS ON IMPSTS.ID=PEXT.[Categoría de Impuestos_ID]
LEFT OUTER JOIN     HSVDMDDBPPSQL.MDMHERDEZ.mdm.vwMDM_PD_ComentariosCB COMEN ON COMEN.ID=PEXT.Comentarios_ID
LEFT OUTER JOIN     HSVDMDDBPPSQL.MDMHERDEZ.mdm.vmMDM_Tipo_De_Almacenaje TDALMAC on TDALMAC.ID=PEXT.[Tipo de Almacenaje_ID]
LEFT OUTER JOIN     HSVDMDDBPPSQL.MDMHERDEZ.mdm.vwMDM_PoliticaDeOrden PDO ON PDO.ID= PPLAN.[Cód Política Orden Programa_ID]
LEFT OUTER JOIN     HSVDMDDBPPSQL.MDMHERDEZ.mdm.vwMDM_CódigoDeOrigen CDO ON CDO.ID=PPLAN.[Código Origen M P_ID]
LEFT OUTER JOIN     HSVDMDDBPPSQL.MDMHERDEZ.mdm.vwMDM_CodigoPMP COD_PMP ON  COD_PMP.ID=PPLAN.[Código PMP_ID]
LEFT OUTER JOIN     HSVDMDDBPPSQL.MDMHERDEZ.mdm.vwMDM_TipoMPPlanificacion TMP_PLAN ON TMP_PLAN.ID=PPLAN.[Tipo MP Planificación Prima_ID]
LEFT OUTER JOIN     HSVDMDDBPPSQL.MDMHERDEZ.mdm.vwMDM_Formato_Helados FH on FH.ID=PH.[Codigo de Producto_ID]
LEFT OUTER JOIN     HSVDMDDBPPSQL.MDMHERDEZ.mdm.vwMDM_PD_CATHelados C_H ON C_H.ID= PH.CAT_ID
LEFT OUTER JOIN     HSVDMDDBPPSQL.MDMHERDEZ.mdm.vwMDM_Presentacion_Helados C_P_H on C_P_H.ID =PH.Presentación_ID
LEFT OUTER JOIN  	HSVDMDDBPPSQL.MDMHERDEZ.mdm.vwMDM_UnidadesDeMedida UDM_EAN13_PESO ON  UDM_EAN13_PESO.ID = PCDB.[Unidad Medida Peso EAN 13_ID]
LEFT OUTER JOIN  	HSVDMDDBPPSQL.MDMHERDEZ.mdm.vwMDM_UnidadesDeMedida UDM_EAN13_STD ON  UDM_EAN13_STD.ID = PCDB.[Unidad Medida Estándar EAN 13_ID]
LEFT OUTER JOIN  	HSVDMDDBPPSQL.MDMHERDEZ.mdm.vwMDM_UnidadesDeMedida UDM_EAN13_DIM ON  UDM_EAN13_DIM.ID = PCDB.[Unidad Medida Dimensión EAN 13_ID]
LEFT OUTER JOIN  	HSVDMDDBPPSQL.MDMHERDEZ.mdm.vwMDM_UnidadesDeMedida UDM_DUN14_PESO ON  UDM_DUN14_PESO.ID = PCDB.[Unidad Medida Peso DUN14_ID]
LEFT OUTER JOIN  	HSVDMDDBPPSQL.MDMHERDEZ.mdm.vwMDM_UnidadesDeMedida UDM_DUN14_STD ON  UDM_DUN14_STD.ID = PCDB.[Unidad Medida Estándar DUN14_ID]
LEFT OUTER JOIN  	HSVDMDDBPPSQL.MDMHERDEZ.mdm.vwMDM_UnidadesDeMedida UDM_DUN14_DIM ON  UDM_DUN14_DIM.ID = PCDB.[Unidad Medida Dimensión DUN14_ID]
LEFT OUTER JOIN  	HSVDMDDBPPSQL.MDMHERDEZ.mdm.vwMDM_UnidadesDeMedida UDM_DUN14T_PESO ON  UDM_DUN14T_PESO.ID = PCDB.[Unidad Medida Peso DUN14T_ID]
LEFT OUTER JOIN  	HSVDMDDBPPSQL.MDMHERDEZ.mdm.vwMDM_UnidadesDeMedida UDM_DUN14T_STD ON  UDM_DUN14T_STD.ID = PCDB.[Unidad Medida Estándar DUN14T_ID]
LEFT OUTER JOIN  	HSVDMDDBPPSQL.MDMHERDEZ.mdm.vwMDM_UnidadesDeMedida UDM_DUN14T_DIM ON  UDM_DUN14T_DIM.ID = PCDB.[Unidad Medida Dimensión DUN14T_ID]
WHERE 1=1 

-- 7282




