select * from openQuery(hdz54,'select  * from hdzalm.resmst fetch first 10 row only')
select * from openQuery(hdz54,'select  * from hdzgr2.hf01 fetch first 10 row only')


select * from openQuery(hdz54,'select  * from hdzgr2.hf01 fetch first 10 row only with UR ')

select  * from HSVDMDDB00.MDMHERDEZCI.dbo.vw_get_all_products where [Número de Recurso]='475127'

SELECT
			
			  ISNULL(CAST(MtxRecurso.RMRESC AS Varchar),'')							AS [IDProducto]
			/*Sección Productos Inicio */
			, ISNULL(CAST(MtxRecurso.RMRSCL AS Varchar),'')							AS [Clase]
			, ISNULL(CAST(MtxRecurso.RMWGHT AS Varchar),'')							AS [Peso Bruto]
			, ISNULL(CAST(MtxRecurso.RMRSSC AS varchar), '')						AS [Subclase de recurso]
			, ISNULL(CAST(MtxRecurso.RMNETW AS Varchar),'')							AS [Peso Neto]
			, ISNULL(CAST(MtxRecurso.RMWTUM AS Varchar),'')							AS [Unidad de Medida de Peso]
			, ISNULL(CAST(MtxRecurso.RMUMSR AS Varchar),'')							AS [Unidad de Medida Estándar]
			, ISNULL(CAST(MtxRecurso.RMMIS2 AS Varchar),'')							AS [Piezas P Unidad de Venta]
			--, ISNULL(CAST(MtxRecurso.RMDTMT AS Varchar),'')							AS [Fecha de último Mtto] 
			, ISNULL(CAST(MtxRecurso.RMABCC AS Varchar),'')							AS [Código ABC]
			, ISNULL(CAST(MtxRecurso.RMMIS3 AS Varchar),'')							AS [Empaque Contenido]
			, ISNULL(CAST(MtxRecurso.RMLOTC AS Varchar),'')							AS [Control de Lote]
			--, ISNULL(CAST(MtxRecurso.RMDTAB AS Varchar),'')							AS [Fecha Actualización ABC]
			, ''																	AS [Fecha Actualización ABC]
			, ISNULL(CAST(MtxRecurso.RMBCON AS Varchar),'')							AS [Consumo en Lote]
			, ISNULL(CAST(LTRIM(MtxRecurso.RMMKPL) AS Varchar),'')					AS [Linea]
			, ISNULL(CAST(MtxRecurso.RMSHTG AS Varchar),'')							AS [Indicador insuficiencia]
			, ISNULL(CAST(MtxRecurso.RMBORC AS Varchar),'')							AS [Código Saldo Recurso]
			, ISNULL(CAST(MtxRecurso.RMTHEO AS Varchar),'')							AS [Consumo Teórico]
			, ISNULL(CAST(MtxRecurso.RMPRCL AS Varchar),'')							AS [Clase Producto Producción]
			, ISNULL(CAST(MtxRecurso.RMPOTR AS Varchar),'')							AS [Recurso Potente]
			, ISNULL(CAST(MtxRecurso.RMPOTF AS Varchar),'')							AS [Factor de Potencia]
			, ISNULL(CAST(MtxRecurso.RMBEDT AS Varchar),'')							AS [Fecha Efectividad Inicial]
			, ISNULL(CAST(MtxRecurso.RMEEDT AS Varchar),'')							AS [Fecha Efectividad Final]
			, ISNULL(CAST(MtxRecurso.RMSFCT AS Varchar),'')							AS [Factor Merma]
			, ISNULL(CAST(MtxRecurso.RMJIT AS Varchar),'')							AS [Justo a Tiempo]
			, ISNULL(CAST(MtxRecurso.RMBOLH AS Varchar),'')							AS [Peligro BOL]
			, ISNULL(CAST(MtxRecurso.RMPRPL AS Varchar),'')							AS [Línea Prod Producción]
			, ISNULL(CAST(MtxRecurso.RMTXCC AS Varchar),'')							AS [Catégoria de Impuesto]
			, ISNULL(CAST(MtxRecurso.RMMIS1 AS Varchar),'')							AS [Status]
			, ISNULL(CAST(MtxRecurso.RMDESC AS Varchar),'')							AS [Descripción del Recurso]
			/*Sección Productos Fin */

			/*Sección Productos Almacen Inicio */
			, ISNULL(CAST(MtxRecurso.RMSUTR AS Varchar),'')							AS [Cantidad Estiba x Hilera]
			, ISNULL(CAST(MtxRecurso.RMSUUN AS Varchar),'')							AS [Cantidad Estiba x Unidad]
			, ISNULL(CAST(MtxRecurso.CAMASXTARIUNCARGA AS Varchar),'')				AS [Cantidad de Camas x Tarima]
			, ISNULL(CAST(MtxRecurso.RMSTHT AS Varchar),'')							AS [Altura de Estiba]
			, ISNULL(CAST(MtxRecurso.RMAGD1 AS Varchar),'')							AS [Días Antigüedad 1]
			, ISNULL(CAST(MtxRecurso.RMHTSU AS Varchar),'')							AS [Caja Altura]
			, ISNULL(CAST(MtxRecurso.RMWDSU AS Varchar),'')							AS [Caja Ancho]
			, ISNULL(CAST(MtxRecurso.RMDPSU AS Varchar),'')							AS [Caja Profundidad]
			, ISNULL(CAST(MtxRecurso.RMHTUN AS Varchar),'')							AS [Tarima Altura]
			, ISNULL(CAST(MtxRecurso.RMWDUN AS Varchar),'')							AS [Tarima Ancho]
			, ISNULL(CAST(MtxRecurso.RMDPUN AS Varchar),'')							AS [Tarima Profundidad]
			, ISNULL(CAST(MtxRecurso.RMSTAG AS Varchar),'')							AS [Recurso en Planta]
			, ISNULL(CAST(MtxRecurso.RMRTST AS Varchar),'')							AS [Rotación Inventario]
			, ISNULL(CAST(MtxRecurso.RMWNDW AS Varchar),'')							AS [Ventana de Envío Directo]
			/*Sección Productos Almacen Fin */

			/*Sección Productos Aseg. Calidad Inicio */
			, ISNULL(CAST(MtxRecurso.RMSHLB AS Varchar),'')		AS [Vida Útil]
			, ISNULL(CAST(MtxRecurso.RMSHLD AS Varchar),'')		AS [Vida útil - Días]
			, ISNULL(CAST(MtxRecurso.RMDCPO AS Varchar),'')		AS [Recep Misc Cód Clasific Localiz Predet]
			, ISNULL(CAST(MtxRecurso.RMDCPR AS Varchar),'')		AS [Recep Prod Cód Clasific Localiz Predet]
			
			/*Sección Productos Aseg. Calidad Fin */

			/*Sección Productos C. Adicionales Inicio */

			--, ISNULL(CAST(MtxRecurso.RMSFTM AS Varchar),'')		AS [Tiempo de seguridad]
			--, ISNULL(CAST(MtxRecurso.RMRPCL AS Varchar),'')		AS [Clase de reporte]
			--, ISNULL(CAST(MtxRecurso.RMDOCU AS Varchar),'')		AS [Cód de localiz docum]
			--, ISNULL(CAST(MtxRecurso.RMMKCL AS Varchar),'')		AS [Cls Recurso Mercadeo]
			--, ISNULL(CAST(MtxRecurso.RMSICL AS Varchar),'')		AS [Cód clase inven est]
			--, ISNULL(CAST(MtxRecurso.RMSWCS AS Varchar),'')		AS [Cambio Sobre Costo]
			--, ISNULL(CAST(MtxRecurso.RMVORT AS Varchar),'')		AS [Tasa GI Variable]
			--,ISNULL(CAST(MtxRecurso.RMVOTV AS Varchar),'')		AS [Valor Tabla GI Var]
			--,ISNULL(CAST(MtxRecurso.RMVOPD AS Varchar),'')		AS [Byte GI Variable]
			--,ISNULL(CAST(MtxRecurso.RMVOTR AS Varchar),'')		AS [Tabla Tasa GI Varibl]
			--,ISNULL(CAST(MtxRecurso.RMFORT AS Varchar),'')		AS [Tasa GI Fija]
			--,ISNULL(CAST(MtxRecurso.RMFOTV AS Varchar),'')		AS [Valor Tabla GI Fija]
			--,ISNULL(CAST(MtxRecurso.RMFOPD AS Varchar),'')		AS [Byte GI Fijo]
			--,ISNULL(CAST(MtxRecurso.RMFOTR AS Varchar),'')		AS [Tabla Tasa GI Fijo]
			--,ISNULL(CAST(MtxRecurso.RMNVAL AS Varchar),'')		AS [Valor Neto Reablizab]
			--,ISNULL(CAST(MtxRecurso.RMFIXC AS Varchar),'')		AS [Costo Fijo]
			--,ISNULL(CAST(MtxRecurso.RMDFWC AS Varchar),'')		AS [Ctro Trabajo X Omis]
			--,ISNULL(CAST(MtxRecurso.RMDSHG AS Varchar),'')		AS [Grupo Turno X Omisi]
			--,ISNULL(CAST(MtxRecurso.RMNOPM AS Varchar),'')		AS [N Veces Recurs Usado]
			--,ISNULL(CAST(MtxRecurso.RMCMLT AS Varchar),'')		AS [TE Acum MP Cst Prim]
			--,ISNULL(CAST(MtxRecurso.RMLTHR AS Varchar),'')		AS [TE Acum MP Cst Pr hr]
			--,ISNULL(CAST(MtxRecurso.RMLTMN AS Varchar),'')		AS [TE Acum MP Cst Pr mn]
			--,ISNULL(CAST(MtxRecurso.RMATSK AS Varchar),'')		AS [Nmb Tarea Escand rl]
			--,ISNULL(CAST(MtxRecurso.RMSTSK AS Varchar),'')		AS [Nmb Tarea Escand Sim]
			--,ISNULL(CAST(MtxRecurso.RMPLSQ AS Varchar),'')		AS [N Secuencia Planif]
			--,ISNULL(CAST(MtxRecurso.RMDLCO AS Varchar),'')		AS [Loc Omis p Consumo]
			--,ISNULL(CAST(MtxRecurso.RMDWCO AS Varchar),'')		AS [Alm Omis p Consumo]
			--,ISNULL(CAST(MtxRecurso.RMCOMM AS Varchar),'')		AS [Código de mercancía]

			--,ISNULL(CAST(MtxRecurso.RMCREV AS Varchar),'')		AS [Nivel Revisión Actl]
			--,ISNULL(CAST(MtxRecurso.RMEREV AS Varchar),'')		AS [Ultimo Nivel Aceptab]
			--,ISNULL(CAST(MtxRecurso.RMBUYR AS Varchar),'')		AS [Número de comprador]
			--,ISNULL(CAST(MtxRecurso.RMSERV AS Varchar),'')		AS [Nivel Servicio A]
			--,ISNULL(CAST(MtxRecurso.RMCAPM AS Varchar),'')		AS [Multiplic Capacidad]
			--,ISNULL(CAST(MtxRecurso.RMRFCL AS Varchar),'')		AS [Rqd De Cd Clsif Lclz]
			--,ISNULL(CAST(MtxRecurso.RMPLT1 AS Varchar),'')		AS [TE 1 de OC]
			--,ISNULL(CAST(MtxRecurso.RMPHR1 AS Varchar),'')		AS [TE 1 OC hrs]
			--,ISNULL(CAST(MtxRecurso.RMPMN1 AS Varchar),'')		AS [TE 1 OC mns]
			--,ISNULL(CAST(MtxRecurso.RMPLT2 AS Varchar),'')		AS [TE 2 OC]
			--,ISNULL(CAST(MtxRecurso.RMPHR2 AS Varchar),'')		AS [TE 2 OC hrs]
			--,ISNULL(CAST(MtxRecurso.RMPMN2 AS Varchar),'')		AS [TE 2 OC mns]
			--,ISNULL(CAST(MtxRecurso.RMPLTN AS Varchar),'')		AS [TE OC p Nva Versión]
			--,ISNULL(CAST(MtxRecurso.RMPHRN AS Varchar),'')		AS [TE OC Nva Ver hrs]
			--,ISNULL(CAST(MtxRecurso.RMPMNN AS Varchar),'')		AS [TE OC Nva Ver mns]
			--,ISNULL(CAST(MtxRecurso.RMMLT1 AS Varchar),'')		AS [TE 1 MO]
			--,ISNULL(CAST(MtxRecurso.RMMHR1 AS Varchar),'')		AS [TE 1 MO hrs]
			--,ISNULL(CAST(MtxRecurso.RMMMN1 AS Varchar),'')		AS [TE 1 MO mns]
			--,ISNULL(CAST(MtxRecurso.RMMLT2 AS Varchar),'')		AS [TE 2 MO]
			--,ISNULL(CAST(MtxRecurso.RMMHR2 AS Varchar),'')		AS [TE 2 MO hrs]
			--,ISNULL(CAST(MtxRecurso.RMMMN2 AS Varchar),'')		AS [TE 2 MO mns]
			--,ISNULL(CAST(MtxRecurso.RMPLTA AS Varchar),'')		AS [Ajustar TE OC Day]
			--,ISNULL(CAST(MtxRecurso.RMPHRA AS Varchar),'')		AS [Ajustar TE OC hrs]
			--,ISNULL(CAST(MtxRecurso.RMPMNA AS Varchar),'')		AS [Ajustar TE OC mns]
			--,ISNULL(CAST(MtxRecurso.RMMLTA AS Varchar),'')		AS [Ajustar TE MO day]
			--,ISNULL(CAST(MtxRecurso.RMMHRA AS Varchar),'')		AS [Ajustar TE MO hrs]
			--,ISNULL(CAST(MtxRecurso.RMMMNA AS Varchar),'')		AS [Ajustar TE OM mns]
			--,ISNULL(CAST(MtxRecurso.RMPOQY AS Varchar),'')		AS [Cnt Máxima TE OC]
			--,ISNULL(CAST(MtxRecurso.RMMOQY AS Varchar),'')		AS [Cnt Máxima TE MO]
			--,ISNULL(CAST(MtxRecurso.RMSLLT AS Varchar),'')		AS [TE Ventas]
			--,ISNULL(CAST(MtxRecurso.RMSLHR AS Varchar),'')		AS [TE Ventas hrs]
			--,ISNULL(CAST(MtxRecurso.RMSLMN AS Varchar),'')		AS [TE Ventas mns]
			--,ISNULL(CAST(MtxRecurso.RMGRAP AS Varchar),'')		AS [Código de gráficos]
			--,ISNULL(CAST(MtxRecurso.RMDLPR AS Varchar),'')		AS [Loc Omis p Bolt Prd]
			--,ISNULL(CAST(MtxRecurso.RMDWPR AS Varchar),'')		AS [Alm Omis p Bolt Prd]
			--,ISNULL(CAST(MtxRecurso.RMCOM1 AS Varchar),'')		AS [Código 1 Cmt Omis]
			--,ISNULL(CAST(MtxRecurso.RMCOM2 AS Varchar),'')		AS [Código 2 Cmt Omis]
			--,ISNULL(CAST(MtxRecurso.RMCOM3 AS Varchar),'')		AS [Código 3 Cmt Omis]
			--,ISNULL(CAST(MtxRecurso.RMINQT AS Varchar),'')	AS [Acept Var Cnt Inv]
			--,ISNULL(CAST(MtxRecurso.RMDFIQ AS Varchar),'')	AS [Var Cnt Inv Omis]
			--,ISNULL(CAST(MtxRecurso.RMFRQT AS Varchar),'') 	AS [Var Cnt Bol Cmplt]
			----,ISNULL(CAST(MtxRecurso.RMDFFQ AS Varchar),'')    AS [Aplica Var Cnt Bol Cmplt]
			--,ISNULL(CAST(MtxRecurso.RMINQT AS Varchar),'')		AS [Acept Var Preci Inv]
			--,ISNULL(CAST(MtxRecurso.RMDFIP AS Varchar),'')		AS [Var Precio Inv Omi]
			--,ISNULL(CAST(MtxRecurso.RMURQT AS Varchar),'')		AS [Var Cnt Défct Acep]
			--,ISNULL(CAST(MtxRecurso.RMDFUQ AS Varchar),'')		AS [Var Cnt Défic Oms]
			--,ISNULL(CAST(MtxRecurso.RMORQT AS Varchar),'')		AS [Var Cnt sbr recp]
			--,ISNULL(CAST(MtxRecurso.RMDFOQ AS Varchar),'')		AS [Var Cnt SR Oms]
			--,ISNULL(CAST(MtxRecurso.RMZONE AS Varchar),'')		AS [Días Zona Firme]
			--,ISNULL(CAST(MtxRecurso.RMUNPR AS Varchar),'')		AS [Precio Unit Omisión]
			--,ISNULL(CAST(MtxRecurso.RMRTTB AS Varchar),'')		AS [Tabla Fch Rotación]
			--,ISNULL(CAST(MtxRecurso.RMFRCL AS Varchar),'')		AS [Clasif de transp]
			--,ISNULL(CAST(MtxRecurso.RMRCLS AS Varchar),'')		AS [Reclasif Automática]
			--,ISNULL(CAST(MtxRecurso.RMAGD2 AS Varchar),'')		AS [Días Antigüedad 2]
			--,ISNULL(CAST(MtxRecurso.RMAGD3 AS Varchar),'')		AS [Días Antigüedad 3]
			--,ISNULL(CAST(MtxRecurso.RMAGD4 AS Varchar),'')		AS [Días Antigüedad 4]
			--,ISNULL(CAST(MtxRecurso.RMAGD5 AS Varchar),'')		AS [Días Antigüedad 5]
			--,ISNULL(CAST(MtxRecurso.RMDSTL AS Varchar),'')		AS [Loclzcn Planta]
			--,ISNULL(CAST(MtxRecurso.RMCHEM AS Varchar),'')		AS [Fórmula química]
			--,ISNULL(CAST(MtxRecurso.RMPRCA AS Varchar),'')		AS [IMPRIM C A]
			--,ISNULL(CAST(MtxRecurso.RMCASN AS Varchar),'')		AS [Núm caja]
			--,ISNULL(CAST(MtxRecurso.RMRGCT AS Varchar),'')		AS [Categoría reglamet]
			--,ISNULL(CAST(MtxRecurso.RMSPDI AS Varchar),'')		AS [Trans DI Grp Substit]
			--,ISNULL(CAST(MtxRecurso.RMSPRC AS Varchar),'')		AS [Trans RC Grp Substit]
			--,ISNULL(CAST(MtxRecurso.RMUNIV AS Varchar),'')		AS [Recurso Universal]
			--,ISNULL(CAST(MtxRecurso.RMINQD AS Varchar),'')		AS [N Días Adel Cons DAC]
			--,ISNULL(CAST(MtxRecurso.RMSCFM AS Varchar),'')		AS [Familia Programas]
			--,ISNULL(CAST(MtxRecurso.CODIGODEBARRAS3 AS Varchar),'')		AS [CODIGODEBARRAS3]
			--,ISNULL(CAST(MtxRecurso.CODIGODEBARRAS4 AS Varchar),'')		AS [CODIGODEBARRAS4]
			--,ISNULL(CAST(MtxRecurso.CODIGODEBARRAS5 AS Varchar),'')		AS [CODIGODEBARRAS5]
			--,ISNULL(CAST(MtxRecurso.CODIGODEBARRAS6 AS Varchar),'')		AS [CODIGODEBARRAS6]
			--,ISNULL(CAST(MtxRecurso.CODIGODEBARRAS7 AS Varchar),'')		AS [CODIGODEBARRAS7]
			--,ISNULL(CAST(MtxRecurso.CODIGODEBARRAS9 AS Varchar),'')		AS [CODIGODEBARRAS9]
			--,ISNULL(CAST(MtxRecurso.CODIGODEBARRAS10 AS Varchar),'')		AS [CODIGODEBARRAS10]
			--,ISNULL(CAST(MtxRecurso.UNIDADMEDIDAUNIDADLOGISTICA03 AS Varchar),'')		AS [UNIDADMEDIDAUNIDADLOGISTICA03]
			--,ISNULL(CAST(MtxRecurso.UNIDADMEDIDAUNIDADLOGISTICA04 AS Varchar),'')		AS [UNIDADMEDIDAUNIDADLOGISTICA04]
			--,ISNULL(CAST(MtxRecurso.UNIDADMEDIDAUNIDADLOGISTICA05 AS Varchar),'')		AS [UNIDADMEDIDAUNIDADLOGISTICA05]
			--,ISNULL(CAST(MtxRecurso.UNIDADMEDIDAUNIDADLOGISTICA06 AS Varchar),'')		AS [UNIDADMEDIDAUNIDADLOGISTICA06]
			--,ISNULL(CAST(MtxRecurso.UNIDADMEDIDAUNIDADLOGISTICA07 AS Varchar),'')		AS [UNIDADMEDIDAUNIDADLOGISTICA07]
			--,ISNULL(CAST(MtxRecurso.UNIDADMEDIDAUNIDADLOGISTICA09 AS Varchar),'')		AS [UNIDADMEDIDAUNIDADLOGISTICA09]
			--,ISNULL(CAST(MtxRecurso.UNIDADMEDIDAUNIDADLOGISTICA10 AS Varchar),'')		AS [UNIDADMEDIDAUNIDADLOGISTICA10]
			/*Sección Productos C. Adicionales Fin */

			/*Sección Productos Código Barra Inicio*/
			
			, RIGHT('000000000000000' + ISNULL(CAST(  MtxRecurso.CODBARRASUNCONSUMO AS Varchar),''),15)		AS [CB EAN13]
			,ISNULL(CAST(MtxRecurso.PESONETOCB1 AS Varchar),'')				AS [Peso Neto EAN 13]
			,ISNULL(CAST(MtxRecurso.PESOBRUTOCB1 AS Varchar),'')				AS [Peso Bruto EAN 13]
			,ISNULL(CAST(MtxRecurso.UNIDADMEDIDAUNIDADPESO01 AS Varchar),'')			AS [Unidad Medida Peso EAN 13]
			,ISNULL(CAST(MtxRecurso.UNIDADMEDIDAUNIDADLOGISTICA01 AS Varchar),'')		AS [Unidad Medida Estándar EAN 13]
			,ISNULL(CAST(MtxRecurso.UNIDADMEDIDACB1 AS Varchar),'')						AS [Unidad Medida Dimensión EAN 13]
			,ISNULL(CAST(MtxRecurso.VOLUMENEXTCB1 AS Varchar),'')						AS [Volúmen Exterior EAN 13]
			,ISNULL(CAST(MtxRecurso.DIMINTALTOCB1 AS Varchar),'')				AS [Dimensión Interior Alto EAN 13]
			,ISNULL(CAST(MtxRecurso.DIMEXTALTOCB1 AS Varchar),'')				AS [Dimensión Ext Alto EAN 13]
			,ISNULL(CAST(MtxRecurso.DIMINTANCCB1 AS Varchar),'')				AS [Dimensión Interior Ancho EAN 13]
			,ISNULL(CAST(MtxRecurso.DIMEXTANCCB1 AS Varchar),'')				AS [Dimensión Ext Ancho EAN 13]
			,ISNULL(CAST(MtxRecurso.DIMINTPROFCB1 AS Varchar),'')				AS [Dimensión Interior Profundo EAN 13]
			,ISNULL(CAST(MtxRecurso.DIMEXTPROFCB1 AS Varchar),'')				AS [Dimensión Ext Profundo EAN 13]
			,ISNULL(CAST(MtxRecurso.UNIDADMEDIDAUNIDADPESO02 AS Varchar),'')	AS [Unidad Medida Peso DUN14]
			,ISNULL(CAST(MtxRecurso.PESONETOCB2 AS Varchar),'')					AS [Peso Neto DUN14]
			,ISNULL(CAST(MtxRecurso.PESOBRUTOCB2 AS Varchar),'')				AS [Peso Bruto DUN14]
			, RIGHT ('000000000000000' + ISNULL(CAST(MtxRecurso.CODBARRASUNEXPEDICION AS Varchar),''), 15)	AS [CB DUN14]
			,ISNULL(CAST(MtxRecurso.UNIDADMEDIDAUNIDADLOGISTICA02 AS Varchar),'')		AS [Unidad Medida Estándar DUN14]
			,ISNULL(CAST(MtxRecurso.UNIDADMEDIDACB2 AS Varchar),'')			AS [Unidad Medida Dimensión DUN14]
			,ISNULL(CAST(MtxRecurso.VOLUMENEXTCB2 AS Varchar),'')		AS [Volúmen Exterior DUN14]
			,ISNULL(CAST(MtxRecurso.DIMINTALTOCB2 AS Varchar),'')		AS [Dimensión Interior Alto DUN14]
			,ISNULL(CAST(MtxRecurso.DIMEXTALTOCB2 AS Varchar),'')		AS  [Dimensión Ext Alto DUN14]
			,ISNULL(CAST(MtxRecurso.DIMINTANCCB2 AS Varchar),'')		AS [Dimensión Interior Ancho DUN14]
			,ISNULL(CAST(MtxRecurso.DIMEXTANCCB2 AS Varchar),'')		AS [Dimensión Ext Ancho DUN14]
			,ISNULL(CAST(MtxRecurso.DIMINTPROFCB2 AS Varchar),'')		AS [Dimensión Interior Profundo DUN14]
			,ISNULL(CAST(MtxRecurso.DIMEXTPROFCB2 AS Varchar),'')		AS [Dimensión Ext Profundo DUN14]
			,ISNULL(CAST(MtxRecurso.UNIDADMEDIDAUNIDADPESO08 AS Varchar),'')		AS [Unidad Medida Peso DUN14T]
			,ISNULL(CAST(MtxRecurso.UNIDADMEDIDAUNIDADLOGISTICA08 AS Varchar),'')	AS [Unidad Medida Estándar DUN14T]
			,RIGHT( '000000000000000' + ISNULL(CAST(MtxRecurso.CODBARRASUNCARGA AS Varchar),''), 15)		AS [CB DUN14T]
			,ISNULL(CAST(MtxRecurso.PESONETOCB8 AS Varchar),'')		AS [Peso Neto DUN14T]
			,ISNULL(CAST(MtxRecurso.PESOBRUTOCB8 AS Varchar),'')		AS [Peso Bruto DUN14T]
			,ISNULL(CAST(MtxRecurso.UNIDADMEDIDACB8 AS Varchar),'')		AS [Unidad Medida Dimensión DUN14T]
			,ISNULL(CAST(MtxRecurso.VOLUMENEXTCB8 AS Varchar),'')		AS [Volúmen Exterior DUN14T]
			,ISNULL(CAST(MtxRecurso.DIMINTALTOCB8 AS Varchar),'')		AS [Dimensión Interior Alto DUN14T]
			,ISNULL(CAST(MtxRecurso.DIMINTANCCB8 AS Varchar),'')		AS [Dimensión Interior Ancho DUN14T]
			,ISNULL(CAST(MtxRecurso.DIMINTPROFCB8 AS Varchar),'')		AS [Dimensión Interior Profundo DUN14T]
			,ISNULL(CAST(MtxRecurso.DIMEXTALTOCB8 AS Varchar),'')		AS [Dimensión Ext Alto DUN14T]
			,ISNULL(CAST(MtxRecurso.DIMEXTANCCB8 AS Varchar),'')		AS [Dimensión Ext Ancho DUN14T]
			,ISNULL(CAST(MtxRecurso.DIMEXTPROFCB8 AS Varchar),'')		AS [Dimensión Ext Profundo DUN14T]

			/*Sección Productos Código Barra Fin*/
			/*Sección Productos Comentario Inicio*/
			--,ISNULL(CAST(MtxRecurso.RNDTMT AS Varchar),'')		AS [Fecha de último Mtto]
			--,ISNULL(CAST(MtxRecurso.RNSEQN AS Varchar),'')		AS [No]
			--,ISNULL(CAST(MtxRecurso.RNCNMT AS Varchar),'')		AS [Comentario]
			/*Sección Productos Comentario Fin*/
			/*Sección Productos Compras Inicio*/
			
			,ISNULL(CAST(MtxRecurso.RMUMPR AS Varchar),'')		AS [UM Compras]
			,ISNULL(CAST(MtxRecurso.RMVNAP AS Varchar),'')		AS [Cód Aprob Proveedor Y N]
			,ISNULL(CAST(MtxRecurso.RMTAXC AS Varchar),'')		AS [Código Imponible]
			/*Sección Productos Compras Fin*/

			/*Sección Productos Costos Inicio*/
			,ISNULL(CAST(MtxRecurso.RMFCLC AS Varchar),'')	AS [Código Nivel Costeo Fijo]
			--,ISNULL(CAST(MtxRecurso.RMCSTP AS Varchar),'')		AS [Código Tipo Acum Costo] --C,N
			,ISNULL(CAST(MtxRecurso.RMSTDC AS Varchar),'')		AS [Costo Estándar_A]
			,ISNULL(CAST(MtxRecurso.RMSTDC_GPO AS Varchar),'')		AS [Costo Estándar_G]
			--,ISNULL(CAST(MtxRecurso.RMDTLR AS Varchar),'')	AS [Fecha Última Acumulación]
			,ISNULL(CAST(MtxRecurso.RMCLC AS Varchar),'')		AS [Código Nivel Costeo]
			,ISNULL(CAST(MtxRecurso.RMSELC AS Varchar),'')		AS [Costo Unitario Seleccionado]
			,ISNULL(CAST(MtxRecurso.RMPVCS AS Varchar),'')		AS [Costo Última Acumulación]
			,ISNULL(CAST(MtxRecurso.RMNRVL AS Varchar),'')		AS [Uso Valor Neto Realiz]
			,ISNULL(CAST(MtxRecurso.RMCRLC AS Varchar),'')		AS [Cód Clase Nivel Acum Cost] --C,N
			,ISNULL(CAST(MtxRecurso.RMRCST AS Varchar),'')		AS [Nuevo Costeo]
			,ISNULL(CAST(MtxRecurso.RMCSRU AS Varchar),'')		AS [Mét Costeo Acum Costo]
			,ISNULL(CAST(MtxRecurso.RMPCTP AS Varchar),'')		AS [Tipo MP Prim p Costo]
			,ISNULL(CAST(MtxRecurso.RMPCNM AS Varchar),'')		AS [Nmb MP Prim p Costo]

			/*Sección Productos Costos Fin*/
			/*Sección Productos Extendido Inicio*/

			,ISNULL(CAST(MtxRecurso.DEPRODUCTO_GPO AS Varchar),'')		AS [Descripción Larga del Producto]
			,ISNULL(CAST(MtxRecurso.NUFICHATECNICA AS Varchar),'')		AS [Número Ficha Técnica]
			,ISNULL(CAST(MtxRecurso.UNIDADEMPAQUE AS Varchar),'')		AS [Unidad Empaque]
			,ISNULL(CAST(MtxRecurso.TIEMPAQUEPRIM AS Varchar),'')		AS [Tipo Empaque Primario]
			,ISNULL(CAST(MtxRecurso.CASA AS Varchar),'')		AS [Clave de Marca]
			,ISNULL(CAST(MtxRecurso.CIAALFA AS Varchar),'')		AS [Clave Compañía Alfanum]
			,ISNULL(CAST(MtxRecurso.CIA AS Varchar),'')		AS [Número de Compañía]
			,ISNULL(CAST(MtxRecurso.COMPANIAAMECE AS Varchar),'')		AS [Compañía AMECE]
			,ISNULL(CAST(MtxRecurso.RMSELP AS Varchar),'')		AS [Precio de Venta]
			,ISNULL(CAST(MtxRecurso.NOPRODUCTO AS Varchar),'')		AS [Número del Producto]
			,ISNULL(CAST(MtxRecurso.CODBARRASUNCONSUMO AS Varchar),'')		AS [EAN13]
			,ISNULL(CAST(MtxRecurso.CODBARRASUNEXPEDICION AS Varchar),'')		AS [DUN14]
			,ISNULL(CAST(MtxRecurso.CODBARRASUNCARGA AS Varchar),'')		AS [DUN14T]
			,ISNULL(CAST(MtxRecurso.CATIMPUESTOS2 AS Varchar),'')		AS [Categoría de Impuestos]

			/*Sección Productos Extendido Fin*/

			/*Sección Productos Planeación Inicio*/

			,''	AS [Cód Política Orden Programa]
			,ISNULL(CAST(MtxRecurso.RMORPL AS Varchar),'')	AS [Cód Política Orden Programa_A]
			,ISNULL(CAST(MtxRecurso.RMORPL_GPO AS Varchar),'')	AS [Cód Política Orden Programa_G]

			,ISNULL(CAST(MtxRecurso.RMWHFM AS Varchar),'')		AS [Código Origen M P]
			,ISNULL(CAST(MtxRecurso.RMWHFM AS Varchar),'') AS [Código Origen M P_A]
			,ISNULL(CAST(MtxRecurso.RMWHFM_GPO AS Varchar),'') AS [Código Origen M P_G]
			,ISNULL(CAST(MtxRecurso.RMPLAN AS Varchar),'')		AS [Número de Planificador]
			,ISNULL(CAST(MtxRecurso.RMORAM AS Varchar),'')		AS [Cantidad Orden Prog Fijo]
			,''		AS [Indicador Nueva Planif]
			,ISNULL(CAST(MtxRecurso.RMREPL AS Varchar),'')      AS [Indicador Nueva Planif_A]
			,ISNULL(CAST(MtxRecurso.RMREPL_GPO AS Varchar),'')      AS [Indicador Nueva Planif_G]
			,ISNULL(CAST(MtxRecurso.RMMNPQ AS Varchar),'')		AS [Ctn Orden Progr Min]
			,ISNULL(CAST(MtxRecurso.RMSFST AS Varchar),'')		AS [Inventario de Seguridad]
			,ISNULL(CAST(MtxRecurso.RMMSPC AS Varchar),'')  		AS [Código PMP]
			,ISNULL(CAST(MtxRecurso.RMMSPC AS Varchar),'')      AS [Código PMP_A]
			,ISNULL(CAST(MtxRecurso.RMMSPC_GPO AS Varchar),'')      AS [Código PMP_G]
			,ISNULL(CAST(MtxRecurso.RMMXPQ AS Varchar),'')		AS [Ctn Orden Progr Máx]
			--,ISNULL(CAST(MtxRecurso.RMPPTP AS Varchar),'')		AS [Tipo MP Planificación Prima]
			,ISNULL(CAST(MtxRecurso.RMPPNM AS Varchar),'')		AS [Nombre MP Planif Prima]
			,ISNULL(CAST(MtxRecurso.RMMPFT AS Varchar),'')		AS [Ctn Orden Progr Mul]
			,ISNULL(CAST(MtxRecurso.RMPLVB AS Varchar),'')		AS [Cód Nivel Planif Fijo]
			,ISNULL(CAST(MtxRecurso.RMPLVC AS Varchar),'')		AS [Cód Nivel Planificación]
			,ISNULL(CAST(MtxRecurso.RMSTPC AS Varchar),'')		AS [Código Plazo Corto]
			,ISNULL(CAST(MtxRecurso.RMLTPC AS Varchar),'')		AS [Código Plazo Largo]
			,ISNULL(CAST(MtxRecurso.RMRCLT AS Varchar),'')		AS [Calc de Nvo Tiempo Espera]
			,ISNULL(CAST(MtxRecurso.RMITPC AS Varchar),'')		AS [Código Plazo Intermedio]
			,ISNULL(CAST(MtxRecurso.RMPEGC AS Varchar),'')		AS [Código de Identificación]
			,ISNULL(CAST(MtxRecurso.RMORDY AS Varchar),'')		AS [Días de Abastecimiento]
			/*Sección Productos Planeación Fin*/	
FROM       (
            SELECT   RESMST1.*, RESMSA.*, RESMST2.RMSTDC AS RMSTDC_GPO, RESMST2.RMORPL AS RMORPL_GPO
				   , RESMST2.RMWHFM AS RMWHFM_GPO, RESMST2.RMMSPC AS RMMSPC_GPO, RESMST2.RMREPL AS RMREPL_GPO	,	RESMSA2.DEPRODUCTO	 AS DEPRODUCTO_GPO					
			FROM            openQuery(HDZ54,'SELECT  * FROM HDZALM.RESMST WITH UR ') RESMST1
			LEFT JOIN       openQuery(HDZ54,'SELECT  * FROM HDZGPO.RESMST WITH UR ')  RESMST2 ON RESMST2.RMRESC = RESMST1.RMRESC
			LEFT OUTER JOIN openQuery(HDZ54,'SELECT  * FROM HDZALM.RESMSA WITH UR ') RESMSA ON RESMSA.NOPRODUCTO = RESMST1.RMRESC
			LEFT OUTER JOIN openQuery(HDZ54,'SELECT  * FROM HDZGPO.RESMSA WITH UR ') RESMSA2 ON RESMSA2.NOPRODUCTO = RESMST1.RMRESC
			) MtxRecurso

			SELECT COUNT(1) FROM  openQuery(HDZ54,'SELECT  * FROM HDZALM.RESMST WITH UR ') --9949
			SELECT COUNT(1) FROM BS_AS400--9949